// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActiveController from "./active_controller"
application.register("active", ActiveController)

import AutosubmitController from "./autosubmit_controller"
application.register("autosubmit", AutosubmitController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PasswordController from "./password_controller"
application.register("password", PasswordController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import UpdateInputController from "./update_input_controller"
application.register("update-input", UpdateInputController)
